FROM solr:5.3

MAINTAINER  istern

COPY resources/schema.xml /opt/solr/server/solr/configsets/basic_configs/conf 

run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_core_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_master_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_web_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_fxm_master_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_fxm_web_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_list_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_marketing_asset_index_master 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_marketing_asset_index_web 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_marketingdefinitions_master 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_marketingdefinitions_web 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_suggested_test_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/sitecore_testing_index 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/social_messages_master 
run cp -r /opt/solr/server/solr/configsets/basic_configs/ /opt/solr/server/solr/social_messages_web 